{"_id":{"$oid":"5f7d4841634d6111143d8190"},"messages":[],"username":"cakejhan","passwordHash":"$2a$10$TUbcIv5HWwd7rxJIbIEmJuWutS81W4bb38X8aWATsABszmFd5kGu6","displayName":"cakejhan","__v":{"$numberInt":"0"}}